sudo: false

cache:
  directories:
    - $HOME/.stack

matrix:
  include:
  - env: STACK_YAML=stack.yaml

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - travis_wait stack --no-terminal setup
  - travis_wait stack build --no-terminal --test --no-run-tests --bench --no-run-benchmarks
  - stack test
  - stack bench
